### PR TITLE
root may be as substring

### PR DESCRIPTION
**Pull request by abugov**
This change is [Reviewable](https://reviewable.io/reviews/qualisystems/cloudshell-hp-alm/22)

### CODE REVIEW

**Comment by abugov** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[CloudShellApi/Api.cs, line 57 at r1](https://reviewable.io:443/reviews/qualisystems/cloudshell-hp-alm/22#-Kd1EfAuKsCF9AFIrLyc:-Kd1EfAuKsCF9AFIrLyd:bafdg69) ([raw file](https://github.com/qualisystems/cloudshell-hp-alm/blob/5fa0f28e3542bfcf7ffe99c8d69ee621dfd7f6e9/CloudShellApi/Api.cs#L57)):*
> ```Smalltalk
>             {
>                 string password = Config.OverridePassword;
>                 return password == null ? m_UserName : m_UserPassword;
> ```

bug here

---

*[CloudShellApi/Api.cs, line 64 at r1](https://reviewable.io:443/reviews/qualisystems/cloudshell-hp-alm/22#-Kd1Em9KTNnU0BXY9o7K:-Kd1Em9KTNnU0BXY9o7L:bmejrh6) ([raw file](https://github.com/qualisystems/cloudshell-hp-alm/blob/5fa0f28e3542bfcf7ffe99c8d69ee621dfd7f6e9/CloudShellApi/Api.cs#L64)):*
> ```Smalltalk
>         {
>             isSuccess = false;
>             string connectProperty = "url = '" + CurrentlUrl + "', domain = '" + m_Domain +
> ```

rename CurrentlUrl to CurrentUrl

---

*[CloudShellApi/Api.cs, line 123 at r1](https://reviewable.io:443/reviews/qualisystems/cloudshell-hp-alm/22#-Kd1F6z4Dr8dtEK6Otll:-Kd1F6z4Dr8dtEK6Otlm:bkc03r0) ([raw file](https://github.com/qualisystems/cloudshell-hp-alm/blob/5fa0f28e3542bfcf7ffe99c8d69ee621dfd7f6e9/CloudShellApi/Api.cs#L123)):*
> ```Smalltalk
>             contentError = "";
> 
>             if (parentPath == null || parentPath == "")
> ```

use string.IsNullOrEmpty instead

---

*[CloudShellApi/Api.cs, line 126 at r1](https://reviewable.io:443/reviews/qualisystems/cloudshell-hp-alm/22#-Kd1F2ej8C0t4qCG5jfO:-Kd1F2ej8C0t4qCG5jfP:bkc03r0) ([raw file](https://github.com/qualisystems/cloudshell-hp-alm/blob/5fa0f28e3542bfcf7ffe99c8d69ee621dfd7f6e9/CloudShellApi/Api.cs#L126)):*
> ```Smalltalk
>             {
>                 string root = Config.TestsRoot;
>                 if(root != null && root != "")
> ```

use string.IsNullOrEmpty instead

---

*[TestType4DotNet/TestShellTestsBrowserForm.cs, line 22 at r1](https://reviewable.io:443/reviews/qualisystems/cloudshell-hp-alm/22#-Kd1FizedpzO-OxZRvxi:-Kd1FizedpzO-OxZRvxj:b-ntvrey) ([raw file](https://github.com/qualisystems/cloudshell-hp-alm/blob/5fa0f28e3542bfcf7ffe99c8d69ee621dfd7f6e9/TestType4DotNet/TestShellTestsBrowserForm.cs#L22)):*
> ```Smalltalk
>     {
>         //private string m_CurrentTestPath = null;
>         Api m_Api;
> ```

change to "readonly Api m_Api"

---

*[TestType4DotNet/TestShellTestsBrowserForm.cs, line 229 at r1](https://reviewable.io:443/reviews/qualisystems/cloudshell-hp-alm/22#-Kd1FsZeykXYywLqnFe6:-Kd1FsZeykXYywLqnFe7:bcip5l3) ([raw file](https://github.com/qualisystems/cloudshell-hp-alm/blob/5fa0f28e3542bfcf7ffe99c8d69ee621dfd7f6e9/TestType4DotNet/TestShellTestsBrowserForm.cs#L229)):*
> ```Smalltalk
>                     curPath = curPath + arrPath[i];
>                     //if (i != arrPath.Length)
>                     {
> ```

cleanup comment and un-needed "{"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/cloudshell-hp-alm/22)*

**Comment by AndreyMHP** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[CloudShellApi/Api.cs, line 64 at r1](https://reviewable.io:443/reviews/qualisystems/cloudshell-hp-alm/22#-Kd1Em9KTNnU0BXY9o7K:-Kd1H8qyItc1ohtnmJp3:b-p7qeef) ([raw file](https://github.com/qualisystems/cloudshell-hp-alm/blob/5fa0f28e3542bfcf7ffe99c8d69ee621dfd7f6e9/CloudShellApi/Api.cs#L64)):*
<details><summary><i>Previously, abugov (Abugov) wrote…</i></summary><blockquote>

rename CurrentlUrl to CurrentUrl
</blockquote></details>

its ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/cloudshell-hp-alm/22)*

**Comment by abugov** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[CloudShellApi/Api.cs, line 57 at r1](https://reviewable.io:443/reviews/qualisystems/cloudshell-hp-alm/22#-Kd1EfAuKsCF9AFIrLyc:-Kd1X-EaeV7e3Ft5g_hw:b-896fix) ([raw file](https://github.com/qualisystems/cloudshell-hp-alm/blob/5fa0f28e3542bfcf7ffe99c8d69ee621dfd7f6e9/CloudShellApi/Api.cs#L57)):*
<details><summary><i>Previously, abugov (Abugov) wrote…</i></summary><blockquote>

bug here
</blockquote></details>

Done.

---

*[CloudShellApi/Api.cs, line 64 at r1](https://reviewable.io:443/reviews/qualisystems/cloudshell-hp-alm/22#-Kd1Em9KTNnU0BXY9o7K:-Kd1WzS4bYkb_g9K6A28:b-896fix) ([raw file](https://github.com/qualisystems/cloudshell-hp-alm/blob/5fa0f28e3542bfcf7ffe99c8d69ee621dfd7f6e9/CloudShellApi/Api.cs#L64)):*
<details><summary><i>Previously, AndreyMHP wrote…</i></summary><blockquote>

its ok
</blockquote></details>

Done.

---

*[TestType4DotNet/TestShellTestsBrowserForm.cs, line 22 at r1](https://reviewable.io:443/reviews/qualisystems/cloudshell-hp-alm/22#-Kd1FizedpzO-OxZRvxi:-Kd1Wus5rGuyanIgG_g3:b-896fix) ([raw file](https://github.com/qualisystems/cloudshell-hp-alm/blob/5fa0f28e3542bfcf7ffe99c8d69ee621dfd7f6e9/TestType4DotNet/TestShellTestsBrowserForm.cs#L22)):*
<details><summary><i>Previously, abugov (Abugov) wrote…</i></summary><blockquote>

change to "readonly Api m_Api"
</blockquote></details>

Done.

---

*[TestType4DotNet/TestShellTestsBrowserForm.cs, line 229 at r1](https://reviewable.io:443/reviews/qualisystems/cloudshell-hp-alm/22#-Kd1FsZeykXYywLqnFe6:-Kd1Wwqi3neLtXD3sWlu:b-896fix) ([raw file](https://github.com/qualisystems/cloudshell-hp-alm/blob/5fa0f28e3542bfcf7ffe99c8d69ee621dfd7f6e9/TestType4DotNet/TestShellTestsBrowserForm.cs#L229)):*
<details><summary><i>Previously, abugov (Abugov) wrote…</i></summary><blockquote>

cleanup comment and un-needed "{"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/cloudshell-hp-alm/22)*

**Comment by abugov** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[CloudShellApi/Api.cs, line 123 at r1](https://reviewable.io:443/reviews/qualisystems/cloudshell-hp-alm/22#-Kd1F6z4Dr8dtEK6Otll:-Kd1XHc0Vfcof47Ik3F1:b-896fix) ([raw file](https://github.com/qualisystems/cloudshell-hp-alm/blob/5fa0f28e3542bfcf7ffe99c8d69ee621dfd7f6e9/CloudShellApi/Api.cs#L123)):*
<details><summary><i>Previously, abugov (Abugov) wrote…</i></summary><blockquote>

use string.IsNullOrEmpty instead
</blockquote></details>

Done.

---

*[CloudShellApi/Api.cs, line 126 at r1](https://reviewable.io:443/reviews/qualisystems/cloudshell-hp-alm/22#-Kd1F2ej8C0t4qCG5jfO:-Kd1XHAEjpUI4gaZNref:b-896fix) ([raw file](https://github.com/qualisystems/cloudshell-hp-alm/blob/5fa0f28e3542bfcf7ffe99c8d69ee621dfd7f6e9/CloudShellApi/Api.cs#L126)):*
<details><summary><i>Previously, abugov (Abugov) wrote…</i></summary><blockquote>

use string.IsNullOrEmpty instead
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/cloudshell-hp-alm/22)*

**Comment by abugov** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[CloudShellApi/Api.cs, line 57 at r1](https://reviewable.io:443/reviews/qualisystems/cloudshell-hp-alm/22#-Kd1EfAuKsCF9AFIrLyc:-Kd1XNxXxDdTOB_MpeMB:b-896fix) ([raw file](https://github.com/qualisystems/cloudshell-hp-alm/blob/5fa0f28e3542bfcf7ffe99c8d69ee621dfd7f6e9/CloudShellApi/Api.cs#L57)):*
<details><summary><i>Previously, abugov (Abugov) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---

*[CloudShellApi/Api.cs, line 64 at r1](https://reviewable.io:443/reviews/qualisystems/cloudshell-hp-alm/22#-Kd1Em9KTNnU0BXY9o7K:-Kd1XOVAOW-f1-3nJH8x:b-896fix) ([raw file](https://github.com/qualisystems/cloudshell-hp-alm/blob/5fa0f28e3542bfcf7ffe99c8d69ee621dfd7f6e9/CloudShellApi/Api.cs#L64)):*
<details><summary><i>Previously, abugov (Abugov) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/cloudshell-hp-alm/22)*

**Comment by AndreyMHP** [comment]
Reviewed 3 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/cloudshell-hp-alm/22)*

**Comment by AndreyMHP** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/cloudshell-hp-alm/22)*

**Pull request merged**
