### PR TITLE
Added IsRunSuccess. Move Get Json object text to separate template me…

### PR DESCRIPTION
**Pull request by abugov**
…thod.

---
This change is [Reviewable](https://reviewable.io/reviews/qualisystems/cloudshell-hp-alm/26)

### CODE REVIEW

**Comment by abugov** [comment]
Review status: 0 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[CloudShellApi/Api.cs, line 232 at r1](https://reviewable.io:443/reviews/qualisystems/cloudshell-hp-alm/26#-KdQqkxDwJWLBIIATDOn:-KdQqkxDwJWLBIIATDOo:by16eeu) ([raw file](https://github.com/qualisystems/cloudshell-hp-alm/blob/24951378369cbbfe3fb6fc0ee1b33b504811f170/CloudShellApi/Api.cs#L232)):*
> ```Smalltalk
> 
>         public ApiSuiteDetails IsRunSuccess(string m_RunGuid, out string contentError, out bool isSuccess)
>         {
> ```

rename to "GetRunResult"

---

*[CloudShellApi/Api.cs, line 276 at r1](https://reviewable.io:443/reviews/qualisystems/cloudshell-hp-alm/26#-KdQsm8x6hoV-x3IUPqE:-KdQsm8x6hoV-x3IUPqF:bc8dxmb) ([raw file](https://github.com/qualisystems/cloudshell-hp-alm/blob/24951378369cbbfe3fb6fc0ee1b33b504811f170/CloudShellApi/Api.cs#L276)):*
> ```Smalltalk
> 
>         public TestStatus GetTestStatus(string testPath)
>         {
> ```

delete this method

---

*[CloudShellApi/Config.cs, line 66 at r1](https://reviewable.io:443/reviews/qualisystems/cloudshell-hp-alm/26#-KdQt5khQW_XVKj_FAkL:-KdQt5khQW_XVKj_FAkM:b-xvwsj3) ([raw file](https://github.com/qualisystems/cloudshell-hp-alm/blob/24951378369cbbfe3fb6fc0ee1b33b504811f170/CloudShellApi/Config.cs#L66)):*
> ```Smalltalk
>         private Thread m_Worker;
>         private Api m_Api;
> ```

read only

---

*[CloudShellApi/Config.cs, line 117 at r1](https://reviewable.io:443/reviews/qualisystems/cloudshell-hp-alm/26#-KdQtsPWazo1bT7VnCyG:-KdQtsPWazo1bT7VnCyH:b3uhcze) ([raw file](https://github.com/qualisystems/cloudshell-hp-alm/blob/24951378369cbbfe3fb6fc0ee1b33b504811f170/CloudShellApi/Config.cs#L117)):*
> ```Smalltalk
>                 return false;
>             }
>             if (apiSuiteStatusDetails.SuiteStatus == "Ended")
> ```

Logger.Debug

---

*[CloudShellApi/Config.cs, line 139 at r1](https://reviewable.io:443/reviews/qualisystems/cloudshell-hp-alm/26#-KdQuHUev0fU4zJcKMRW:-KdQuHUev0fU4zJcKMRX:b-xt7igr) ([raw file](https://github.com/qualisystems/cloudshell-hp-alm/blob/24951378369cbbfe3fb6fc0ee1b33b504811f170/CloudShellApi/Config.cs#L139)):*
> ```Smalltalk
>                 case "Completed":
>                     return ExecutionJobResult.Completed;
>                 case "CompletedWithError/EndedWithErrors":
> ```

separate to 2

---

*[Tester/Form1.cs, line 26 at r1](https://reviewable.io:443/reviews/qualisystems/cloudshell-hp-alm/26#-KdQuPt1EdHPBghx4RfL:-KdQuPt1EdHPBghx4RfM:b-mi56ke) ([raw file](https://github.com/qualisystems/cloudshell-hp-alm/blob/24951378369cbbfe3fb6fc0ee1b33b504811f170/Tester/Form1.cs#L26)):*
> ```Smalltalk
>             string contentError;
>             bool isSuccess;
>             string GuiId = m_Api.RunTest(m_ScriptControl.TestPath, out contentError, out isSuccess);
> ```

guid instead of GuId

---

*[CTT4ALM1152.sln, line 23 at r1](https://reviewable.io:443/reviews/qualisystems/cloudshell-hp-alm/26#-KdQqIfw9kmzleWdmd7S:-KdQqIfw9kmzleWdmd7T:b-tapdti) ([raw file](https://github.com/qualisystems/cloudshell-hp-alm/blob/24951378369cbbfe3fb6fc0ee1b33b504811f170/CTT4ALM1152.sln#L23)):*
> ```
> 	ProjectSection(ProjectDependencies) = postProject
> 		{C290F38C-AFD1-420B-9CC6-BB1EED921500} = {C290F38C-AFD1-420B-9CC6-BB1EED921500}
> 	EndProjectSection
> ```

do u know that is this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/cloudshell-hp-alm/26)*

**Comment by AndreyMHP** [comment]
Reviewed 6 of 7 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/cloudshell-hp-alm/26)*

**Comment by AndreyMHP** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/cloudshell-hp-alm/26)*

**Comment by abugov** [comment]
Reviewed 2 of 7 files at r1, 2 of 2 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/cloudshell-hp-alm/26)*

**Pull request merged**
